services:
  python-requirements:
    build:
      context: .
    image: python-requirements:latest
    volumes:
      - .:/app/
    networks:
      - backend

  jupyter-lab:
    image: python-requirements:latest
    depends_on:
      python-requirements:
        condition: service_started
    volumes:
      - .:/app/
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root -NotebookApp.token='' --NotebookApp.password=''
    networks:
      - backend

  mlflow:
    image: python-requirements:latest
    depends_on:
      python-requirements:
        condition: service_started
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    command: mlflow server --host 0.0.0.0 --port 8080
    networks:
      - backend

  streamlit:
    image: python-requirements:latest
    depends_on:
      python-requirements:
        condition: service_started
    volumes:
      - .:/app/
    ports:
      - "8501:8501"
    command: streamlit run src/streamlit/welcome.py --server.address 0.0.0.0
    networks:
      - backend

networks:
  backend: