services:
  python-requirements:
    build: .
    networks:
      - backend

  jupyter-lab:
    image: ml-infrastructure-python-requirements:latest
    volumes:
      - .:/app/
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root -NotebookApp.token='' --NotebookApp.password=''
    networks:
      - backend

  mlflow:
    image: ml-infrastructure-python-requirements:latest
    volumes:
      - .:/app/
    ports:
      - "8080:8080"
    command: mlflow server --host 0.0.0.0 --port 8080
    networks:
      - backend

networks:
  backend: